# Структуры и алгоритмы

Структуры - объекты, хранящие в себе однотипные данные. Рассмотрим некоторые из них.

## Списки

Списки бывают односвязные (самые простые) и двусвязные. 

In [ ]:
# elem1 -> elem2 -> elem3...
# elem1 -> elem2 -> elem3
#       <-       <-

In [1]:
class LinkedList():
  def __init__(self, value):
    self.next = None
    self.value = value

  def bind_next(self, other):
    self.next = other

  def print_all(self):
    curr_node = self
    vals = []
    while curr_node:
      vals.append(curr_node.value)
      curr_node = curr_node.next
    print(vals)

class DoubleLinkedList():
  def __init__(self, value):
    self.prev = None
    self.next = None
    self.value = value

  def bind_next(self, other):
    self.next = other
    other.prev = self

In [ ]:
ll_1 = LinkedList(0)
ll_2 = LinkedList(1)
ll_3 = LinkedList(2)
ll_4 = LinkedList(3)

ll_1.bind_next(ll_2)
ll_2.bind_next(ll_3)
ll_3.bind_next(ll_4)

# ll_1.next -> ll_2
# ll_2.next -> ll_3
# ll_3.next -> ll_4
# ll_4.next -> None
ll_1.print_all()

[0, 1, 2, 3]


In [ ]:
dll_1 = DoubleLinkedList(0)
dll_2 = DoubleLinkedList(1)
dll_3 = DoubleLinkedList(2)

dll_1.bind_next(dll_2)
dll_2.bind_next(dll_3)

print(dll_1.value, dll_1.next.value, dll_1.next.next.value)
print(dll_3.value, dll_3.prev.value, dll_3.prev.prev.value)

0 1 2
2 1 0


In [ ]:
def do_smth_v1(data):
  if data.value > 1:
     return True
  else:
    return False

for item in data:
  do_smth_v1(item)
  # if ...

def do_smth_v1(data):
  if data.value > 1:
     return True
  elif data.next is None:
      return True
  else:
    return False  

# data[index], data[index+1], ..
# item.next.next ..

Какие операции можно провернуть со списками? Можно добавлять элемент, удалять элемент, находить элемент и т.д.

In [ ]:
# elem1 -> elem2 -> elem3
# DELETE elem2 ? elem1 -> elem3
# ADD elem2.5 ? elem1 -> elem2 -> elem2.5 -> elem3

# elem1 (0) <-> elem2 (1) <->elem3 (2)
# while True:
#   curr_node = curr_node.next
#   if curr_node.value == target:
#      curr_node.prev.next = curr_node.next
#      curr_node.next.prev = curr_node.prev

# curr_node = elem1
# curr_node = elem1.next = elem2
# elem1.next = elem2.next
# elem3.prev = elem2.prev

In [ ]:
def LinkedList_delete(curr_node, value):
  head = curr_node
  temp = curr_node

  if temp:
      if (temp.value == value):
          head = temp.next
          temp = None
          return head


  while temp:
      if temp.value == value:
          break
      prev = temp
      temp = temp.next

  if not temp:
      return

  prev.next = temp.next

  return head

In [ ]:
LinkedList_delete(ll_1, 1).print_all()

есть односвязный список; как узнать, что у нас в нем нет циклов?

In [ ]:
# e1 -> e2 -> e3 -> e4
#       ^           |
#       |           |
#       -------------

In [ ]:
class LinkedList_flag():
  def __init__(self, value):
    self.next = None
    self.value = value
    self.checked = False

visited = ["e1", "e2", "e3", "e4", "e2"]

# 3: e3 e3 e3 ...
# 2: e2 e4 e3 
# ДЗ

## Стеки

Last in - first out (LIFO)

In [ ]:
class Stack():
  def __init__(self):
    self.values = []
  
  def put(self, value):
    self.values.append(value)

  def pop(self):
    print(self.values[len(self.values)-1])
    self.values = self.values[:len(self.values)-1]

In [ ]:
s = Stack()
s.put(3)
s.put(5)
s.put(7)
s.pop()
s.pop()
s.pop()

7
5
3


## Очереди

First in - first out (FIFO)

In [ ]:
class Queue():
  def __init__(self):
    self.values = []
  
  def put(self, value):
    self.values.append(value)

  def pop(self):
    print(self.values[0])
    self.values = self.values[1:]

In [ ]:
q = Queue()
q.put(3)
q.put(5)
q.put(7)
q.pop()
q.pop()
q.pop()

3
5
7


In [ ]:
# service 1 (2), service 2 (100)
# service 1 -> service 2
# 1) http
# 2) DB
# 3) q (rabbitMQ, kafka)

## Деревья

In [ ]:
# [1-6]
# MIN?
min = data[0]
for item in data:
  if item < min:
    min = item

max = data[0]
for item in data:
  if item > min:
    max = item

#         5
#       3   6
#    1   4    
#       2

#      5
#     4 6
#    3
#   2
#  1

In [ ]:
# 1-10

#      1
#        2
#          3
#  .............

In [ ]:
class BinaryTreeNode():
  def __init__(self, value):
    self.l = None
    self.r = None
    self.value = value

  def print(self):
    print(self.value)
    if self.l:
      print("left for", self.value)
      self.l.print()
    if self.r:
      print("right for", self.value)
      self.r.print()

class BinaryTree():
  def __init__(self):
    self.root = None

  def add(self, value):
    if not self.root:
        self.root = BinaryTreeNode(value)
        return
    
    def _add(node, value):
      if node.value > value:
        if node.l:
          _add(node.l, value)
        else:
          node.l = BinaryTreeNode(value)
      else:
        if node.r:
          _add(node.r, value)
        else:
          node.r = BinaryTreeNode(value)
    
    _add(self.root, value)
  
  def print_all(self):
    self.root.print()

In [ ]:
t = BinaryTree()
t.add(5)
t.add(4)
t.add(1)
t.add(8)
t.add(6)
t.add(9)

In [ ]:
t.print_all()

5
left for 5
4
left for 4
1
right for 5
8
left for 8
6
right for 8
9


## Оценка

Обычно алгоритмы оценивают, делают это по:
- памяти
- сложности

https://leetcode.com/problemset/all/?sorting=W3sic29ydE9yZGVyIjoiQVNDRU5ESU5HIiwib3JkZXJCeSI6IkRJRkZJQ1VMVFkifV0%3D

https://www.codewars.com/

Оценка по памяти заключается в ответе на вопрос, сколько нужно будет выделить памяти для решения задачи (n -> inf)

пусть есть массив чисел; хотим убрать все нечетные



In [ ]:
def bad_clear(data):
  new_data = []
  for item in data:
    if item % 2 == 0:
      new_data.append(item)

  return new_data

# [0 3 4 1 7 8 11 4 5]
# i end
# 0 8
# 1 8 [0 5 4 1 7 8 11 4 3]
# 1 7 [0 4 4 1 7 8 11 5 3]
# 1 6
# 2 6
# 3 6 [0 4 4 11 7 8 1 5 3]
# 3 5 [0 4 4 8 7 11 1 5 3]
# 3 4
# 4 4 [0 4 4 8 7 11 1 5 3]
# 4 3
def good_clear(data):
  i = 0
  end = len(data)

  while i < end:
    if data[i] % 2 == 0:
      i += 1
    else:
      data[i], data[end-1] = data[end-1], data[i]
      end -= 1

  return data[:end]

In [ ]:
data_1 = [2,4,6,8,10,12]
print(bad_clear(data_1))
print(good_clear(data_1))

[2, 4, 6, 8, 10, 12]
[2, 4, 6, 8, 10, 12]


In [ ]:
data_2 = [1,5,2,4,9,10,2,8,1]
print(bad_clear(data_2))
print(good_clear(data_2))

[2, 4, 10, 2, 8]
[8, 2, 2, 4, 10]


In [ ]:
data_3 = [1,5,7,11,5,7,21,2]
print(bad_clear(data_3))
print(good_clear(data_3))

[2]
[2]


Оценка по сложности заключается в ответе на вопрос, сколько времени займет решение проблемы (n -> inf)

In [ ]:
# [1 4 2 6]
# [1 2 4 6]

In [ ]:
def bubble_sort(data):
  for i in range(len(data)):
    for j in range(len(data)-i-1):
      if data[j] > data[j+1]:
        data[j], data[j+1] = data[j+1], data[j]

In [ ]:
data = [1,3,67,21,3,45,1]
bubble_sort(data)
print(data)

https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DBeoCbJPuvSE&psig=AOvVaw3MIpl3SlvRL8U0Z5FYYxct&ust=1668011058837000&source=images&cd=vfe&ved=0CA0QjRxqFwoTCPjYicf_nvsCFQAAAAAdAAAAABAD

# Паттерны

Паттерн, в общем то, представляет из себя некую конструкцию, которую удобно переиспользовать из раза в раз на разных проектах (так, некоторые паттерны включены изначально в языках)

https://refactoring.guru/ru/design-patterns/catalog

## Синглтон

In [ ]:
logger = None

def new_logger():
  pass

def create_logger():
  if logger:
    return logger
  logger = new_logger()
  return logger

In [ ]:
class Logger():
  logfile = ""

  def __new__(cls, *args, **kwargs):
    if not hasattr(cls, '_logger'):
        cls._logger = super(Logger, cls).__new__(cls)
    # Возвращаем созданный (только что или ранее) объект.
    return cls._logger
    
  def __init__(self):
    pass

# ДЗ

In [ ]:
l = Logger()
l2 = Logger()
print(l is l2)

# l = Logger()
# value = class.__new__()
# class._logger = value
# class.__init__(class._logger)

# l2 = Logger()
# class._logger
# class.__init__(class._logger)

True


## Адаптер

In [ ]:
class ForeignRunner():
  def foreign_run(self):
    return "gninnur"

class MyRunner():
  def run(self):
    return "running"

class Adapter(MyRunner, ForeignRunner):
  def run(self):
    return self.foreign_run()[::-1]

In [ ]:
mr = MyRunner()
mr.run()

'running'

In [ ]:
fr = ForeignRunner()
fr.foreign_run()

'gninnur'

In [ ]:
ar = Adapter()
ar.run()

'running'

## Наблюдатель

In [ ]:
#  class 1 (react to) -> class 2
#  1) class 2 -> DB -> class 1
#  class 1: while True ...
#  2) class 2 -> [] -> class 1
#  ...

In [ ]:
class Child():
  def __init__(self, name):
    self.name = name
    self.state = "calm"
    self.observers = []
    self.shout_count = 0

  def do_smth_good(self):
    print("doing smth")
    self.state = "calm"
    for o in self.observers:
      o.check_state()

  def do_smth_bad(self):
    print("doing smth bad")
    self.state = "not calm"
    for o in self.observers:
      # o.check_state_v2(self)
      o.check_state()

class Parent():
  def __init__(self):
    self.observant = None

  def look_at(self, child):
    self.observant = child
    child.observers.append(self)

  def check_state(self):
    if self.observant.state == "not calm":
      print(self.observant.name.upper())
      self.observant.state = "calm"

  def check_state_v2(self, child):
    if child.state == "not calm":
      print(child.name.upper())
      child.state = "calm"  
  
  def check_state_v3(self, child):
    if child.state == "not calm":
      print(child.name.upper())
      child.shout_count += 1
      if child.shout_count == len(child.observers):
        child.state = "calm"
        child.shout_count = 0 


In [ ]:
c = Child("Alice")
p1 = Parent()
p2 = Parent()
p1.look_at(c)
p2.look_at(c)

In [ ]:
actions = [0,0,0,1,0,1,1,0]
for a in actions:
  if a == 0:
    c.do_smth_good()
  else:
    c.do_smth_bad()

doing smth
doing smth
doing smth
doing smth bad
ALICE
doing smth
doing smth bad
ALICE
doing smth bad
ALICE
doing smth


# Мини домашка

## Задание 1

Хотим найти цикл в односвязном списке; если он есть - возвращаем True, если нет - False
При этом нам нельзя сохранять список уже посещенных нод, хотим сделать проверку в формате, который обсуждали на лекции (идти с разным шагом)

In [5]:
def find_cycle(node):
  pass

In [6]:
ll_1 = LinkedList(0)
ll_2 = LinkedList(1)
ll_3 = LinkedList(2)
ll_4 = LinkedList(3)

ll_1.bind_next(ll_2)
ll_2.bind_next(ll_3)
ll_3.bind_next(ll_4)

assert find_cycle(ll_1) == False

ll_4.bind_next(ll_2)

assert find_cycle(ll_1) == True

## Задание 2

Напишите класс ConnectToDB так, чтобы при передаче уже однажды переданных параметров возвращался созданный ранее экземлпяр класса, при новых - новый

In [14]:
class ConnectToDB():
  connections = {}

  def __new__(cls, *args, **kwargs):
    pass
    
  def __init__(self, address=""):
    self.address = address

In [18]:
c1 = ConnectToDB(address="addr1")
c2 = ConnectToDB(address="addr1")
c3 = ConnectToDB(address="addr2")
assert c1 is c2
assert c1 is not c3